apiVersion: apps/v1
kind: Deployment
metadata:
  name: kekw-deployment
  labels:
    app: kekw
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kekw
  template:
    metadata:
      labels:
        app: kekw
    spec:
      containers:
      - name: kekw
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kekw-service
spec:
  selector:
    app: kekw
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

